{
	"version": 1546593966,
	"fileList": [
		"data.js",
		"c2runtime.js",
		"jquery-2.1.1.min.js",
		"offlineClient.js",
		"images/sprite-sheet0.png",
		"images/lago-sheet0.png",
		"images/personagem-sheet0.png",
		"images/tela-sheet0.png",
		"images/a_personagem-sheet0.png",
		"media/run.ogg",
		"media/back.ogg",
		"media/jump.ogg",
		"media/jump2.ogg",
		"media/atack.ogg",
		"media/atack2.ogg",
		"media/atack3.ogg",
		"media/jump3.ogg",
		"media/jump4.ogg",
		"icon-16.png",
		"icon-32.png",
		"icon-114.png",
		"icon-128.png",
		"icon-256.png",
		"loading-logo.png"
	]
}