{
	"version": 1527125183,
	"fileList": [
		"data.js",
		"c2runtime.js",
		"jquery-2.1.1.min.js",
		"offlineClient.js",
		"images/background-sheet0.png",
		"images/crocodilo-sheet0.png",
		"images/crocodilo-sheet1.png",
		"images/dente1-sheet0.png",
		"images/dente2-sheet0.png",
		"images/menu-sheet0.png",
		"images/b_play-sheet0.png",
		"images/créditos-sheet0.png",
		"images/jogador1-sheet0.png",
		"images/jogador2-sheet0.png",
		"images/b_som-sheet0.png",
		"images/b_musica-sheet0.png",
		"images/creditos-sheet0.png",
		"images/fimj-sheet0.png",
		"images/go-sheet0.png",
		"images/pontuacao-sheet0.png",
		"images/b_menu-sheet0.png",
		"images/b_repetir-sheet0.png",
		"images/t_logo-sheet0.png",
		"images/caneta-sheet0.png",
		"images/empresa-sheet0.png",
		"media/click.m4a",
		"media/click.ogg",
		"media/crocodile sound effect_01.m4a",
		"media/crocodile sound effect_01.ogg",
		"media/awesomeness.ogg",
		"media/awesomeness.m4a",
		"media/bluegrass banjo - country banjo.ogg",
		"media/whatsapp audio 2018-05-23 at 16.09.57.m4a",
		"media/whatsapp audio 2018-05-23 at 16.09.57.ogg",
		"media/bluegrass banjo - country banjo.m4a",
		"icon-16.png",
		"icon-32.png",
		"icon-114.png",
		"icon-128.png",
		"icon-256.png",
		"loading-logo.png"
	]
}